wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/jquery/dist/jquery.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap/dist/js/bootstrap.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/datatables/media/js/jquery.dataTables.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/drmonty-datatables-colvis/js/dataTables.colVis.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/datatables-colreorder/js/dataTables.colReorder.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/patternfly/dist/js/patternfly.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/patternfly-bootstrap-combobox/js/bootstrap-combobox.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap-select/dist/js/bootstrap-select.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap-switch/dist/js/bootstrap-switch.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/bootstrap-treeview/dist/bootstrap-treeview.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/google-code-prettify/bin/prettify.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/jquery-match-height/dist/jquery.matchHeight-min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/systemjs/dist/system-polyfills.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/angular2/bundles/angular2-polyfills.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/es6-shim/es6-shim.min.js
wget     http://wonka.mw.lab.eng.bos.redhat.com/windup-web/node_modules/systemjs/dist/system.js
